"""
Build a fully-static copy of the listing site for GitHub Pages.

Usage:
    python3 freeze.py

Output: ./build/   ← drag-and-drop to Netlify, or push to gh-pages branch.
"""

from app import app
from flask_frozen import Freezer

app.config["FREEZER_DESTINATION"] = "build"
app.config["FREEZER_RELATIVE_URLS"] = True   # makes all hrefs relative — works in any subdir
app.config["FREEZER_REMOVE_EXTRA_FILES"] = True

freezer = Freezer(app)

def _fix_paths(build_dir="build"):
    """
    frozen-flask only converts URLs generated by url_for() — hardcoded
    '/static/...' paths in src/href/CSS attrs keep their leading slash,
    which breaks GitHub Pages subdirectory hosting. Strip the slash from
    all three forms so every asset resolves relative to index.html.
    """
    import pathlib, re
    for html in pathlib.Path(build_dir).rglob("*.html"):
        text = html.read_text()
        # src="/static/..."  →  src="static/..."
        fixed = re.sub(r'\bsrc="/static/', 'src="static/', text)
        # href="/static/..."  →  href="static/..."
        fixed = re.sub(r'\bhref="/static/', 'href="static/', fixed)
        # url('/static/...')  →  url('static/...')   (CSS background-image)
        fixed = re.sub(r"url\('/static/", "url('static/", fixed)
        fixed = re.sub(r'url\("/static/', 'url("static/', fixed)
        if fixed != text:
            html.write_text(fixed)
            print(f"  patched: {html}")

######################################################################
# Set CUSTOM_DOMAIN to your domain once you've bought it, e.g.:
#   CUSTOM_DOMAIN = "2714harvardst.com"
# Leave as None to keep the ricksterz.github.io/2714HarvardSt/ URL.
######################################################################
CUSTOM_DOMAIN = None

if __name__ == "__main__":
    freezer.freeze()
    _fix_paths()

    # Write CNAME file if a custom domain is set
    if CUSTOM_DOMAIN:
        pathlib.Path("build/CNAME").write_text(CUSTOM_DOMAIN + "\n")
        print(f"  wrote CNAME → {CUSTOM_DOMAIN}")

    print("\n✓ Static build written to ./build/")
    print("  Next steps:")
    print("  1. cd build && python3 -m http.server 8000  ← test locally")
    print("  2. Push to GitHub Pages (see README for full commands)")
